// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdagzxypafjlyjeiuedx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkYWd6eHlwYWZqbHlqZWl1ZWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNDk3NjQsImV4cCI6MjA1ODYyNTc2NH0.y31Qm6RS4eL3ulg6Rv_Z5qxPq0oibganJcfVR4B_Ah0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});